Feature/viewsreference support 8.x-2.0-alpha4
LennardWesterveld/graphql-views pull request #1
Opened 2019-01-03 21:52 UTC by eescribanoc

I added support to retrieve the configuration added in viewsreference 8.x-2.0-alpha4 for Limit per page, offset, argument and pager type. I added a way to be able to make influence with offset as well.

This solves a very big head ache I have been having. I tried to create a general solution for the case I needed to use it for.

It was a least a big help your start though, thanks!

2019-01-04 07:14 UTC, LennardWesterveld commented
Nice I will test it and look in to it this weekend!

2019-01-20 12:53 UTC, LennardWesterveld requested changes

2019-01-20 12:53 UTC, LennardWesterveld commented on src/Plugin/GraphQL/Fields/Entity/Fields/View/ViewDerivative.php
> +    $values = $value->getValue();
this seems to be a getter, so i would say that it needs to return also a value without setting it?

2019-01-20 12:53 UTC, LennardWesterveld commented on src/Plugin/GraphQL/Fields/Entity/Fields/View/ViewDerivative.php
> +  protected function setOverridenArguments($value, array &$args) {
Those are not overrides right? it suppose to be default values?

2019-01-29 12:25 UTC, eescribanoc commented on src/Plugin/GraphQL/Fields/Entity/Fields/View/ViewDerivative.php
> +    $values = $value->getValue();
I will better rename the function.

2019-01-29 12:27 UTC, eescribanoc commented on src/Plugin/GraphQL/Fields/Entity/Fields/View/ViewDerivative.php
> +  protected function setOverridenArguments($value, array &$args) {
The default values come from the view configuration. Then we have values that come from graphql queries, and these are values overriden via the viewsreference configuration form, that is why I called them like this. Because I want to be able to override the values set in the view with values set in the viewsreference field configuration form.

Edited:
I changed the name of the function to be more self explainatory and reworked accordingly the code due to the get suggestion.

2019-02-02 15:30 UTC, LennardWesterveld approved these changes

2019-02-02 15:30 UTC, merged